#!/bin/bash
export KBUILD_BUILD_USER=Nathan
export KBUILD_BUILD_HOST=WasHere
export LOCALVERSION="-SE_EK_SS"
echo $KBUILD_BUILD_USER
echo $KBUILD_BUILD_HOST
echo -e "done?"
sleep 2s

make CC=clang ARCH=arm64 O=~/out hatsune_defconfig
make CC=clang LLVM=1 ARCH=arm64 O=~/out -j16 \
        HEADER_ARCH=arm64 \
        SUBARCH=arm64 \
        CXX=c++ \
        AR=llvm-ar \
        NM=llvm-nm \
        OBJDUMP=llvm-objdump \
        STRIP=llvm-strip \
        READELF=llvm-readelf \
        HOSTCXX=clang++ \
        HOSTAR=llvm-ar \
        LLVM_IAS=1 \
        HOSTCFLAGS="-fuse-ld=lld -Wno-unused-command-line-argument" \
        CROSS_COMPILE=~/TC/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-gnu-7.5/bin/aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=~/TC/prebuilts/gcc/linux-x86/arm/arm-linux-gnueabihf-7.5/bin/arm-linux-gnueabihf- \
        CLANG_TRIPLE=~/TC/proton-clang/bin/aarch64-linux-gnu-
