#!/bin/bash
export KBUILD_BUILD_USER="lain"
export KBUILD_BUILD_HOST="iwakura"
export LOCALVERSION="-#LetsAllLoveLain"
echo $KBUILD_BUILD_USER
echo $KBUILD_BUILD_HOST
echo -e "done?"
sleep 5s

make CC=clang ARCH=arm64 O=out hatsune_defconfig
make CC=clang LLVM=1 ARCH=arm64 O=out -j16 \
        HEADER_ARCH=arm64 \
        SUBARCH=arm64 \
        CXX=c++ \
        AR=llvm-ar \
        NM=llvm-nm \
        OBJDUMP=llvm-objdump \
        STRIP=llvm-strip \
        READELF=llvm-readelf \
        HOSTCXX=clang++ \
        HOSTAR=llvm-ar \
        LLVM_IAS=1 \
        HOSTCFLAGS="-fuse-ld=lld -Wno-unused-command-line-argument" \
        CROSS_COMPILE=aarch64-linux-gnu- \
        CROSS_COMPILE_ARM32=arm-linux-gnueabihf- \
        CLANG_TRIPLE=aarch64-linux-gnu-
